// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadNetAgent returns the embedded CollectionSpec for NetAgent.
func LoadNetAgent() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NetAgentBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load NetAgent: %w", err)
	}

	return spec, err
}

// LoadNetAgentObjects loads NetAgent and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*NetAgentObjects
//	*NetAgentPrograms
//	*NetAgentMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadNetAgentObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadNetAgent()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// NetAgentSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetAgentSpecs struct {
	NetAgentProgramSpecs
	NetAgentMapSpecs
}

// NetAgentSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetAgentProgramSpecs struct {
	OnTcpRecvmsg   *ebpf.ProgramSpec `ebpf:"on_tcp_recvmsg"`
	OnTcpSendmsg   *ebpf.ProgramSpec `ebpf:"on_tcp_sendmsg"`
	OnTcpV4Connect *ebpf.ProgramSpec `ebpf:"on_tcp_v4_connect"`
	OnUdpRecvmsg   *ebpf.ProgramSpec `ebpf:"on_udp_recvmsg"`
	OnUdpSendmsg   *ebpf.ProgramSpec `ebpf:"on_udp_sendmsg"`
}

// NetAgentMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetAgentMapSpecs struct {
	Events  *ebpf.MapSpec `ebpf:"events"`
	StartTs *ebpf.MapSpec `ebpf:"start_ts"`
}

// NetAgentObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadNetAgentObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetAgentObjects struct {
	NetAgentPrograms
	NetAgentMaps
}

func (o *NetAgentObjects) Close() error {
	return _NetAgentClose(
		&o.NetAgentPrograms,
		&o.NetAgentMaps,
	)
}

// NetAgentMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadNetAgentObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetAgentMaps struct {
	Events  *ebpf.Map `ebpf:"events"`
	StartTs *ebpf.Map `ebpf:"start_ts"`
}

func (m *NetAgentMaps) Close() error {
	return _NetAgentClose(
		m.Events,
		m.StartTs,
	)
}

// NetAgentPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadNetAgentObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetAgentPrograms struct {
	OnTcpRecvmsg   *ebpf.Program `ebpf:"on_tcp_recvmsg"`
	OnTcpSendmsg   *ebpf.Program `ebpf:"on_tcp_sendmsg"`
	OnTcpV4Connect *ebpf.Program `ebpf:"on_tcp_v4_connect"`
	OnUdpRecvmsg   *ebpf.Program `ebpf:"on_udp_recvmsg"`
	OnUdpSendmsg   *ebpf.Program `ebpf:"on_udp_sendmsg"`
}

func (p *NetAgentPrograms) Close() error {
	return _NetAgentClose(
		p.OnTcpRecvmsg,
		p.OnTcpSendmsg,
		p.OnTcpV4Connect,
		p.OnUdpRecvmsg,
		p.OnUdpSendmsg,
	)
}

func _NetAgentClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed netagent_bpfeb.o
var _NetAgentBytes []byte
